<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIk7Z0Lj\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIk7Z0Lj/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIk7Z0Lj.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIk7Z0Lj\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIk7Z0Lj\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ik7Z0Lj',
    'container.build_id' => 'dab0566f',
    'container.build_time' => 1688635777,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIk7Z0Lj');
