<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUDxcJMO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUDxcJMO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUDxcJMO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUDxcJMO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUDxcJMO\App_KernelDevDebugContainer([
    'container.build_hash' => 'UDxcJMO',
    'container.build_id' => '180a2a93',
    'container.build_time' => 1689149804,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUDxcJMO');
