server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8081

spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/MainDb
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect:
    show-sql: true
  mvc:
    contentnegotiation:
      favor-parameter: true
      favor-path-extension: false
      parameter-name: format
    converters:
      preferred-json-mapper: jackson

  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000