version: '3'

services:
  web:
    build: .
    ports:
      - "8082:80"
    depends_on:
      - database

  ###> doctrine/doctrine-bundle ###
  database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_USER: 'root'
      MYSQL_DATABASE: 'Grendezvous'
    volumes:
      - ./mysql-data2:/var/lib/mysql
    ports:
      - "3306:3306"
  phpmyadmin:
    container_name: 'phpmyadmin'
    image: phpmyadmin/phpmyadmin:5
    restart: always
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: 'root'
    ports:
      - "8088:80"
    depends_on:
      - database

volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###