version: '3'

services:
  web:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - database

  database:
    image:  postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
    volumes:
      - database_data:/var/lib/postgresql/data:rw
volumes:
  database_data:
