

server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8082

spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/MainDb
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true