<?php

namespace ContainerIk7Z0Lj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAppointment2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.hcgmq5R.App\Entity\Appointment' shared service.
     *
     * @return \App\Entity\Appointment
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.hcgmq5R": it needs an instance of "App\\Entity\\Appointment" but this type has been excluded in "config/services.yaml".');
    }
}
