<?php

namespace ContainerY8QeXuT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8S5LSvxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8S5LSvx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8S5LSvx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'appointment' => ['privates', '.errored..service_locator.8S5LSvx.App\\Entity\\Appointment', NULL, 'Cannot autowire service ".service_locator.8S5LSvx": it needs an instance of "App\\Entity\\Appointment" but this type has been excluded in "config/services.yaml".'],
        ], [
            'appointment' => 'App\\Entity\\Appointment',
        ]);
    }
}
