version: '3.8'
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: account_creation
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
    depends_on:
      - postgres
