version: '4.18'
services:
  database:
      healthcheck:
        test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
        interval: 5s
        retries: 5
      container_name: 'database_server'
      image: mysql
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: 'root'
        MYSQL_PASSWORD: 't3rceS'
        MYSQL_DATABASE: 'MainDb'
  myadmin:
    container_name: 'phpmyadmin'
    image: phpmyadmin/phpmyadmin:5
    environment:
      PMA_HOST: database
    ports:
      - "8080:80"
    depends_on:
      - database